### ISSUE TITLE
feat(ODP-2): Implement create and remove build directory commands

### ISSUE THREAD

**Issue by NenadStef** [serbiatech/ci-orb-docker-publisher#4]
# Implement create and prune build directory commands

### Describe Request:

- Implement `src/scripts/set-build-dir.sh` script for creating build directory.
- Implement `src/scripts/remove-build-dir.sh` script for deleting build directory.
- Implement `src/commands/set-build-dir.yml` command configuration.
- Implement `src/commands/remove-build-dir.yml` command configuration.
- Implement `src/tests/set-build-dir.bats` test.
- Implement `src/tests/remove-build-dir.bats` test.
- Add description for both commands.
- Update `CHANGELOG.md`.

### Examples:

This orb should have command configurations for creating and pruning build directory. Command configuration should look something like this:

```yaml
description: >
  This command creates build directory.
parameters:
  buildDir:
    type: string
    default: "./build/"
    description: "Set path to build directory."
steps:
  - run:
      environment:
        BUILD_DIR: <<parameters.buildDir>>
      name: Set Build Directory
      command: echo <<include(scripts/set-build-dir.sh)>>
```
