### ISSUE TITLE
feat(ODP-4): Implement generate build context command

### ISSUE THREAD

**Issue by NenadStef** [serbiatech/ci-orb-docker-publisher#8]
# Implement generate build context for Dockerfiles command

### Describe Request:

- Implement `src/scripts/generate-build-context.sh` script for generating Dockerfile's build context`.
- Implement `src/commands/generate-build-context.yml` command configuration.
- Implement `src/tests/generate-build-context.bats` test.
- Add description for the command.
- Update `CHANGELOG.md`.

### Examples:

This orb should have command configuration for generating `Dockerfiles` build context and saving that context to the `unorderedInheritanceList.txt` that later will be used for building docker images. Command configuration should look something like this:

```yaml
description: >
  This command will generate build context for Dockerfiles.
parameters:
  buildDir:
    type: string
    default: "./build/"
    description: "Path to build directory."
steps:
  - run:
      environment:
        BUILD_DIR: <<parameters.buildDir>>
      name: Generate build context for Dockerfiles
      command: echo <<include(scripts/generate-build-context.sh)>>
```
